[package]
name = "rusty-snake"
version = "0.1.0"
authors = ["Ashton S."]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"

[dependencies.sdl2]
version = "0.34"
default-features = false
features = ["ttf"]